ansistrano:
  container_name: ansistrano
  build: ./../etc/ansistrano

mysql:
  container_name: mysql
  build: ./../etc/mysql
  ports:
    - 3306:3306

########################################################################################################

memcached:
  container_name: memcached
  build: ./../etc/memcached
  ports:
    - 11211
  environment:
    - MEMCACHED_MEMORY_LIMIT=120

########################################################################################################

redis:
  container_name: redis
  build: ./../etc/redis
  ports:
    - 6379:6379


########################################################################################################

elasticsearch:
  container_name: elasticsearch
  build: ./../etc/elasticsearch
  ports:
    - 9300:9300
    - 9200:9200
  environment:
    - PLUGINS=elasticsearch/marvel/latest

########################################################################################################



nginx_php7:
  container_name: nginx_php7
  build: ./../etc/nginx_php7
  ports:
    - 8000:8000
    - 4430:4430
  volumes:
    - ./../var/www:/var/www
    - ./../etc/nginx_php7/helpers/directive-only:/etc/nginx/helpers/directive-only
    - ./../etc/nginx_php7/helpers/location:/etc/nginx/helpers/location
    - ./../etc/nginx_php7/helpers/basic.conf:/etc/nginx/helpers/basic.conf
    - ./../etc/nginx_php7/sites-enabled:/etc/nginx/sites-enabled
  links:
    - redis:redis
    - memcached:memcached
    - mysql:mysql
    - elasticsearch:elasticsearch

########################################################################################################


varnish:
  container_name: varnish
  build: ./../etc/varnish
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./../etc/varnish/templates/default.vcl:/etc/varnish/default.vcl
  links:
    - nginx_php7:nginx_php7

########################################################################################################

rabbitmq:
  container_name: rabbitmq
  build: ./../etc/rabbitmq
  ports:
    - 5672:5672
    - 15672:15672
  volumes:
    - ./../etc/rabbitmq/data/logs:/etc/rabbitmq/data/logs
    - ./../etc/rabbitmq/data/mnesia:/etc/rabbitmq/data/mnesia

########################################################################################################
#nodejs:
#  build: ./../etc/nodejs
#  ports:
#    -
#


#supervisord:
#  build: ./../etc/supervisord
#  ports:
#    -
#

